const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
test('desconto respeita limite, autorização específica, centavos e forma de pagamento', () => {
    const nodes = Object.fromEntries(Object.entries({forma:'avista',percentual:'20',referencia:'ambiente-1',autorizacao:'',resumo:''}).map(([k,value])=>['pagamento-'+k+'-1',{value}]));
    const ctx = {window:{},document:{getElementById:id=>nodes[id]},profissionais:[{id:'V1',descontoMaximo:5}],usuarioAtual:{id:'V1'},formatarMoeda:n=>String(n)};
    vm.createContext(ctx); vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../pagamento.js'),'utf8'),ctx);
    const calcular = () => ctx.window.MichelePagamento.calcular(1,199.99);
    assert.equal(calcular().percentual,5);
    assert.equal(calcular().total,189.99);
    nodes['pagamento-autorizacao-1'].value = JSON.stringify({id:'ok',contexto:{percentual:20,referencia:'ambiente-1',acao:'desconto'}});
    assert.equal(calcular().percentual,20);
    assert.equal(calcular().total,159.99);
    nodes['pagamento-percentual-1'].value='30';
    assert.equal(calcular().percentual,5);
    nodes['pagamento-forma-1'].value='outro';
    assert.equal(calcular().total,199.99);
    assert.equal(calcular().desconto,0);
});
test('cartão limita vendedor a 3x e vincula autorização ao ambiente, bandeira, total e quantidade', () => {
    const nodes = Object.fromEntries(Object.entries({forma:'cartao',percentual:'20',referencia:'ambiente-1',autorizacao:'',resumo:'',parcelas:'12',bandeira:'Visa','autorizacao-parcelas':'',simulacao:'','autorizar-parcelas':'',descricao:''}).map(([k,value])=>['pagamento-'+k+'-1',{value}]));
    nodes['pagamento-parcelas-1'].options = Array.from({length:12},(_,i)=>({value:String(i+1)}));
    const ctx = {window:{},document:{getElementById:id=>nodes[id]},profissionais:[{id:'V1',cargo:'Vendedor',descontoMaximo:5}],usuarioAtual:{id:'V1'},formatarMoeda:n=>String(n)};
    vm.createContext(ctx); vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../pagamento.js'),'utf8'),ctx);
    const calcular = (total=100) => ctx.window.MichelePagamento.calcular(1,total);
    let p = calcular();
    assert.equal(p.parcelas,3); assert.equal(p.desconto,0); assert.equal(p.total,100);
    assert.equal(JSON.stringify(p.valoresParcelas),'[33.33,33.33,33.34]');
    assert.match(nodes['pagamento-simulacao-1'].textContent,/Ainda não autorizada/);
    nodes['pagamento-autorizacao-parcelas-1'].value = JSON.stringify({id:'ok',contexto:{total:100,bandeira:'Visa',parcelas:12,referencia:'ambiente-1',acao:'parcelamento'}});
    p = calcular(); assert.equal(p.parcelas,12);
    assert.equal(Math.round(p.valoresParcelas.reduce((s,n)=>s+n,0)*100),10000);
    assert.equal(p.valoresParcelas[11],8.37);
    assert.equal(calcular(101).parcelas,3);
    nodes['pagamento-bandeira-1'].value='Elo'; assert.equal(calcular().parcelas,3);
    nodes['pagamento-bandeira-1'].value='Visa'; nodes['pagamento-parcelas-1'].value='6'; assert.equal(calcular().parcelas,3);
    ctx.profissionais[0].cargo='Gerente'; assert.equal(calcular().parcelas,6);
    nodes['pagamento-parcelas-1'].value='12'; assert.equal(calcular(101).parcelas,12);
    nodes['pagamento-parcelas-1'].value='13'; assert.equal(calcular().parcelas,1);
    nodes['pagamento-parcelas-1'].value='1'; assert.equal(calcular().valoresParcelas[0],100);
    nodes['pagamento-forma-1'].value='avista'; assert.equal(calcular().parcelas,undefined);
});
